name: Build Pack
on:
  push:
    branches:
      - master 
jobs:
  pack: 
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ windows-latest] 
    steps:
    - uses: actions/checkout@v2 
    - name: Install and Pack 
      run: |
        npm install
        npm run pack
      env:
        GH_TOKEN: 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
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: packs
        path: |
          packs/*exe
